name: ML Model Training Workflow

on: [push]

jobs:
  train:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you need

    - name: Install TensorFlow
      run: |
        python -m pip install --upgrade pip
        pip install tensorflow  # Specify the version if necessary, e.g., tensorflow==2.4.1

    - name: Install Other Dependencies
      run: |
        pip install -r requirements.txt --verbose

    - name: Train Model
      run: python train1.py

    - name: Log Results
      run: echo "Model training complete."
